TOTEM: Mostrar fecha completa de turnos
andes/totem-app pull request #8
Opened 2019-11-11 13:19 UTC by juuliotero

### Requerimiento
* https://proyectos.andes.gob.ar/browse/TOT-6

### Funcionalidad desarrollada 
1. Muestra fecha completa en el listado de turnos
2. Incluye cambios para poder trabajar con las modificaciones en las rutas de la api

### UserStory llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API 
- [X] Si - https://github.com/andes/api/pull/835
- [ ] No

2019-11-15 20:45 UTC, sychus submitted a review, later dismissed
Mejorar este detalle para la lectura de código.

2019-11-15 20:45 UTC, sychus commented on src/app/services/turnos.service.ts
> +      return this.server.patch(this.turnosUrl + '/turno/' + turno.turno._id + '/bloque/' + turno.idBloque + '/agenda/' + turno.idAgenda, datosTurno, options);
Cambiar las concatenaciones utilizando template literals:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2019-11-16 01:56 UTC, juuliotero commented on src/app/services/turnos.service.ts
> +      return this.server.patch(this.turnosUrl + '/turno/' + turno.turno._id + '/bloque/' + turno.idBloque + '/agenda/' + turno.idAgenda, datosTurno, options);
listo!

2019-11-19 17:44 UTC, plammel requested changes

2019-11-19 17:44 UTC, plammel commented on src/app/components/inicio.component.ts
> +    this.agendasService.getAgendas({ prestacion: prestacion.conceptId }).subscribe(agendas => {
Revisar esta linea; no está haciendo nada.

2019-11-20 12:56 UTC, juuliotero commented on src/app/components/inicio.component.ts
> +    this.agendasService.getAgendas({ prestacion: prestacion.conceptId }).subscribe(agendas => {
listo!

2019-11-20 13:08 UTC, plammel approved these changes

2020-01-08 14:18 UTC, merged