TOTEM: Evitar que un paciente pueda sacar más de un turno para la misma prestación
andes/totem-app pull request #9
Opened 2019-11-12 12:05 UTC by juuliotero

### Requerimiento
* https://proyectos.andes.gob.ar/browse/TOT-3

### Funcionalidad desarrollada 
1. Evita que el profesional pueda sacar más de un turno para la misma prestación
2. Si tiene un turno, muestra los datalles del mismo

### UserStory llegó a completarse
- [X] Si
- [ ] No

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API 
- [X] Si 
- [ ] No

2019-11-20 12:48 UTC, plammel requested changes

2019-11-20 12:48 UTC, plammel commented on src/app/components/turnos.component.ts
> +          console.log(this.turnoAsignado);
Remover console.log
```suggestion
```

2019-11-20 12:58 UTC, juuliotero commented on src/app/components/turnos.component.ts
> +          console.log(this.turnoAsignado);
Listo!

2020-01-09 15:58 UTC, kroce approved these changes

2020-01-09 15:59 UTC, merged